# -----------------------------------------------------------------------------
# Project info.
# -----------------------------------------------------------------------------

[project]
name = "dodo-is-api-library"
version = "0.1.1"
description = "API client for DodoIS"
readme = "README.md"
license = {file = "LICENSE"}

# -----------------------------------------------------------------------------
# Build system.
# -----------------------------------------------------------------------------

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# -----------------------------------------------------------------------------
# Dependencies.
# -----------------------------------------------------------------------------

[tool.poetry.dependencies]
python = "^3.12"
aiolimiter = "^1.2.1"
httpx = ">=0.28.1, <1.0.0"
